### ISSUE TITLE
Does trade.isBuyerMaker = true imply this trade was completed by a sell? 

### ISSUE THREAD

**Issue by gebrits** [zoeyg/binance#55]
Am I correct to infer that a trade with `isBuyerMaker = true` implies that this trade was completed by a sell? 
I.e.: a buyer added an order to the depthbook and this trade is completed by a taker of said order (implying a sell) 

Similarly, does `aggTrade.maker= true` imply this aggtrade is completed by a sell?

**Comment by apexearth** [comment]
If `isBuyerMaker` is true then that means a seller fulfilled a buy order. The buyer created the order and waited for someone to fulfill it.

**Comment by gebrits** [comment]
@apexearth : ok thanks, that's a more concise way of putting it :)
Just to be sure `aggTrade.maker= true` means the same correct?

**Comment by wenhuanglin** [comment]
@apexearth : so it means that the type of trade we get is `buy` if `isBuyerMaker = true` ? 
For example if the trade looks like this:
`GET /api/v1/trades?symbol=ETHBTC`
[
 {
    "id": 73641983,
    "price": "0.06710900",
    "qty": "0.64400000",
    "time": 1531916335251,
    "isBuyerMaker": true,
    "isBestMatch": true
  },
]
It is a sell transaction of coin pair ETH/BTC.

**Comment by apexearth** [comment]
The buyer made the order. The seller fulfilled it.

**Comment by tiagosiebler** [comment]
Closing as stale/answered. If needed, feel free to reopen.

**Comment by Dylan-Kerler** [comment]
@wenhuanglin This is a contradiction of what @apexearth is saying.
@apexearth Is saying if `isBuyerMaker` is true then it means that a seller fulfilled the order. In which case it is a sell transaction.
You are saying that `isBuyerMaker` is true then it is a buy transaction.

I would advise updating your post because if I had not scrolled down then I would have got the wrong answer.
Why is the terminology so bad here anyway? It is no intuitive at all. Why not just have a field that says `isBuy`.

**Comment by Bliss3d** [comment]
Yes this should be updated and more precise...

**Comment by eromoe** [comment]
You guys make me confused. I am not native speaker, for me `fulfill` means complete a buy order ?

In another word, which one below is ture?

1. `isBuyerMaker=True` represent a sell operation (may not be all qty settled on that price) ,  and `isBuyerMaker=False` stand for a buy operation.
2.  `isBuyerMaker=True` represent a sell operation which complete a buy order (sell all qty the buy order requires) , and `isBuyerMaker=False` represent a sell operation which doesn't complete a buy order ( left some qty ) .

**Comment by tiagosiebler** [comment]
> You guys make me confused. From https://money.stackexchange.com/questions/90686/what-does-buyer-is-maker-mean , below `1` seems to be right . But some keep saying `fulfilled` make me confused.
> 
> I am not a native speaker, for me `fulfill` means complete a buy order ?

@eromoe the first answer from that stackoverflow link gives a good answer:
> If isBuyerMaker is true for the trade, it means that the order of whoever was on the buy side, was sitting as a bid in the orderbook for some time (so that it was making the market) and then someone came in and matched it immediately (market taker). So, that specific trade will now qualify as SELL and in UI highlight as redish. On the opposite isBuyerMaker=false trade will qualify as BUY and highlight greenish.

It's important to understand here that when you see a "trade" on the exchange, a trade actually involves 2 orders:
- a limit order, waiting in the orderbook, waiting to be filled. This is the maker order. It's making liquidity by waiting in the book.
- a market order, entering the orderbook, trying to get the best possible price immediately. This is the taker order. It's taking liquidity by filling another order in the orderbook.

So every trade you see is actually two orders. One maker order, that's waiting in the orderbook for a taker, and one taker order that's trying to fill immediately at the best possible price.

With this in mind, consider this:
- user1 places a limit buy (order1), which becomes an order on the orderbook.
- user2 places a market sell (order2).
- user2's order2 enters the orderbook as a taker order and immediately matches the order from user1 (order1).
- this means the buyer is the maker, because they were waiting in the orderbook for a fill.
- this also means that both the buyer (maker) and the seller (taker) filled (this is what you see as a trade, isBuyMaker: true)

The same logic works in reverse:
- user1 places a limit sell (order3), becomes an order in the orderbook. This is maker order, since it waits for a fill.
- user2 places a market buy (order4). This is a taker order, because it should fill as soon as possible at the best price.
- order4 enters the orderbook as a taker order and immediately matches the order from user1 (order3)
- this time the seller is the maker, because they were waiting for their order in the orderbook to fill.
- this also means that both the seller (maker) and the buyer (taker) filled (this time isBuyerMaker: false, because the buyer used a market order)

A sell and a buy can both be maker orders. The key point here is if your order is waiting in the orderbook for a fill (e.g. a limit order), or if it's designed to fill as soon as possible (e.g. a market order). Those that wait for a fill are maker orders. Those that fill asap and consume other orders in the orderbook are takers (e.g. market order).

Hope that clears out the confusion.

**Comment by Benk4** [comment]
Hi
Your answer means that if, for example, I place a limit long order and someone sells it to me, then this transaction will be recorded in the completed transactions as a sale, i.e. short. And the fact that I have opened a long position will not be reflected in the list of recent transactions in any way!

> > You guys make me confused. From https://money.stackexchange.com/questions/90686/what-does-buyer-is-maker-mean , below `1` seems to be right . But some keep saying `fulfilled` make me confused.
> > I am not a native speaker, for me `fulfill` means complete a buy order ?
> 
> @eromoe the first answer from that stackoverflow link gives a good answer:
> 
> > If isBuyerMaker is true for the trade, it means that the order of whoever was on the buy side, was sitting as a bid in the orderbook for some time (so that it was making the market) and then someone came in and matched it immediately (market taker). So, that specific trade will now qualify as SELL and in UI highlight as redish. On the opposite isBuyerMaker=false trade will qualify as BUY and highlight greenish.
> 
> It's important to understand here that when you see a "trade" on the exchange, a trade actually involves 2 orders:
> 
> * a limit order, waiting in the orderbook, waiting to be filled. This is the maker order. It's making liquidity by waiting in the book.
> * a market order, entering the orderbook, trying to get the best possible price immediately. This is the taker order. It's taking liquidity by filling another order in the orderbook.
> 
> So every trade you see is actually two orders. One maker order, that's waiting in the orderbook for a taker, and one taker order that's trying to fill immediately at the best possible price.
> 
> With this in mind, consider this:
> 
> * user1 places a limit buy (order1), which becomes an order on the orderbook.
> * user2 places a market sell (order2).
> * user2's order2 enters the orderbook as a taker order and immediately matches the order from user1 (order1).
> * this means the buyer is the maker, because they were waiting in the orderbook for a fill.
> * this also means that both the buyer (maker) and the seller (taker) filled (this is what you see as a trade, isBuyMaker: true)
> 
> The same logic works in reverse:
> 
> * user1 places a limit sell (order3), becomes an order in the orderbook. This is maker order, since it waits for a fill.
> * user2 places a market buy (order4). This is a taker order, because it should fill as soon as possible at the best price.
> * order4 enters the orderbook as a taker order and immediately matches the order from user1 (order3)
> * this time the seller is the maker, because they were waiting for their order in the orderbook to fill.
> * this also means that both the seller (maker) and the buyer (taker) filled (this time isBuyerMaker: false, because the buyer used a market order)
> 
> A sell and a buy can both be maker orders. The key point here is if your order is waiting in the orderbook for a fill (e.g. a limit order), or if it's designed to fill as soon as possible (e.g. a market order). Those that wait for a fill are maker orders. Those that fill asap and consume other orders in the orderbook are takers (e.g. market order).
> 
> Hope that clears out the confusion.

**Comment by tiagosiebler** [comment]
> Hi Your answer means that if, for example, I place a limit long order and someone sells it to me, then this transaction will be recorded in the completed transactions as a sale, i.e. short. And the fact that I have opened a long position will not be reflected in the list of recent transactions in any way!

Orders are always either buys or sells. Long and short are position states, as a result of filling orders. Sticking to that terminology will make it easier to work with systems such as these. 

Otherwise you are correct. If you place a limit buy and a market sell fills your order, the market simply sees a taker sell filled a maker buy. Fills alone aren't enough to know what the position state is for the account with the limit buy. You could be reducing your short, or you could be increasing your long.
