### ISSUE TITLE
keepAliveUserDataStream Error

### ISSUE THREAD

**Issue by yurifontoura** [zoeyg/binance#90]
Today Im getting this error that no got before. Maybe after some update:

`Failed requesting keepAliveUserDataStream for onUserData listener failCount:  1 Error: getaddrinfo EAI_AGAIN api.binance.com
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26) {
  errno: 'EAI_AGAIN',
  code: 'EAI_AGAIN',
  syscall: 'getaddrinfo',
  hostname: 'api.binance.com'
}
`

Any advance help?

**Comment by tiagosiebler** [comment]
Hi Yuri,

The short answer is this looks like a temporary network issue. Every 60 seconds this workflow will send binance a message to keep your user data websocket active. 

"failCount: 1" suggests this was the first time it saw an issue. If you didn't see more of these, it was definitely just temporary.

In case you're curious on the technical side - here's the keep alive logic running on a 60 second timer by default:
https://github.com/zoeyg/binance/blob/master/lib/ws.js#L91

The EAI_AGAIN is a network error suggesting a failed DNS resolution, so for a moment your code couldn't reach api.binance.com because it couldn't resolve the domain:
https://docs.microsoft.com/en-gb/windows/win32/api/ws2tcpip/nf-ws2tcpip-getaddrinfo?redirectedfrom=MSDN#return-value

In my experience it's not fatal unless the error code suggests your listen key is no longer valid, in which case you'll get a different error:
https://github.com/zoeyg/binance/blob/master/lib/ws.js#L96

**Comment by yurifontoura** [comment]
Alright. Thank you Tiago.
